ui:
  # grid items
  container:
    tag: div
    css_class: 'container'

  grid:
    tag: div
    css_class: 'grid'

  row:
    tag: div
    css_class: 'row'
    ui: false

  column:
    tag: div
    css_class: 'wide column'
    ui: false

  # base items
  header:
    tag: div
    css_class: 'header'

  h1:
    tag: h1
    css_class: 'header huge'

  h2:
    tag: h2
    css_class: 'header large'

  h3:
    tag: h3
    css_class: 'header medium'

  h4:
    tag: h4
    css_class: 'header small'

  h5:
    tag: h5
    css_class: 'header'

  h6:
    tag: h6
    css_class: 'header'

  text:
    tag: p
    css_class: 'text'
    ui: false

  icon:
    tag: i
    css_class: 'icon'
    ui: false

  table:
    tag: table
    css_class: table

  thead:
    tag: thead
    css_class: ''
    ui: false

  th:
    tag: th
    css_class: ''
    ui: false

  tr:
    tag: tr
    css_class: ''
    ui: false

  td:
    tag: td
    css_class: ''
    ui: false

  divider:
    tag: div
    css_class: 'divider'

  button:
    tag: button
    css_class: 'button'

  buttons:
    tag: div
    css_class: 'buttons'

  sidebar:
    tag: div
    css_class: 'sidebar'

  menu:
    tag: div
    css_class: 'menu'
    ui: false

  list:
    tag: div
    css_class: 'list'

  checkbox:
    tag: div
    css_class: 'checkbox'

  content:
    tag: div
    css_class: 'content'
    ui: false

  description:
    tag: div
    css_class: 'description'
    ui: false

  segments:
    tag: div
    css_class: 'segments'

  segment:
    tag: div
    css_class: 'segment'

  items:
    tag: div
    css_class: 'items'

  item:
    tag: div
    css_class: 'item'
    ui: false

  cards:
    tag: div
    css_class: 'cards'

  card:
    tag: div
    css_class: 'card'

  breadcrumb:
    tag: div
    css_class: 'breadcrumb'

  form:
    tag: form
    css_class: 'form'

  field:
    tag: div
    css_class: 'field'

  statistics:
    tag: div
    css_class: 'statistics'

  statistic:
    tag: div
    css_class: 'statistic'
    ui: false

  # non semantic ui components

  fragment:
    tag: div
    css_class: fragment
    ui: false

  component:
    tag: div
    css_class: 'component'
    ui: false

  label:
    tag: div
    css_class: 'label'

  value:
    tag: div
    css_class: 'value'
    ui: false

  div:
    tag: div
    ui: false

  small:
    tag: small
    ui: false

  em:
    tag: em
    ui: false


  br:
    tag: br
    ui: false


  p:
    tag: p
    ui: false

  code:
    tag: code
    ui: false

  pre:
    tag: pre
    ui: false

  strong:
    tag: strong
    ui: false

  span:
    tag: span
    ui: false


  component_container:
    tag: div
    ui: false
    css_class: 'flex justify-between items-center'

  component_header:
    tag: h3
    ui: false
    css_class: '!font-mono !mb-0 left-aligned'

  component_counter:
    tag: div
    css_class: 'label circular !bg-black !text-white tiny'

  component_action:
    tag: a
    ui: false
    css_class: 'py-2 px-4 bg-blue-500 text-sm text-white rounded-sm hover:bg-blue-600 hover:text-white border-solid border-2 border-gray-700 no-underline'

  component_return_action:
    tag: a
    ui: false
    css_class: 'py-2 px-4 bg-gray-500 text-sm text-white rounded-sm hover:bg-gray-600 hover:text-gray-100 border-solid border-2 border-gray-700 no-underline'

  component_return_delete_action:
    tag: a
    ui: false
    css_class: 'py-2 px-4 bg-red-500 text-sm text-white rounded-sm hover:bg-red-600 hover:text-red-100 border-solid border-2 border-red-700 no-underline'
