# == Schema Information
#
# Table name: chapters
#
#  id           :bigint           not null, primary key
#  number       :integer          not null
#  summary      :text             not null
#  content      :text
#  book_id      :bigint           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  name         :string
#  plot_summary :text
#

## Functionality
## `plot_summary` is generated by the GenerateBookPlotJob and used by WriteChapterContentJob
## as a part of `content` generation prompt.
##
##
## `summary` is updated by the WriteChapterSummaryJob
## **after** the content has been generated

class Chapter < ApplicationRecord
  belongs_to :book

  scope :rendered, -> { where.not(content: nil) }
  scope :unrendered, -> { where(content: nil) }

  validates :number, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :name, presence: true
  validates :plot_summary, presence: true
  validates :number, uniqueness: { scope: :book_id, message: "should be unique within the book" }
end
