# == Schema Information
#
# Table name: chapters
#
#  id           :bigint           not null, primary key
#  number       :integer          not null
#  summary      :text             not null
#  content      :text
#  book_id      :bigint           not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  name         :string
#  outline      :text
#

## Functionality
## `outline` is generated by the `GenerateBookPlotJob`
## ------
## `RenderBookJob` enques `WriteChaptersJob` for each chapter in order
## `WriteChaptersJob` enques `WriteChapterContentJob` for each chapter in order
## `RenderChapterJob` enques `WriteChapterContentJob` for a given chapter
## ------
## `content` is generated by the `WriteChapterContentJob`
##  |
##  | completing the job enques the `WriteChapterSummaryJob`
##  |
## `summary` is updated by the WriteChapterSummaryJob

class Chapter < ApplicationRecord
  belongs_to :book

  scope :rendered, -> { where.not(content: nil) }
  scope :unrendered, -> { where(content: nil) }

  validates :number, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :name, presence: true
  validates :outline, presence: true
  validates :number, uniqueness: { scope: :book_id, message: "should be unique within the book" }

  def previous_chapter
    book.chapters.where("number < ?", number).order(number: :desc).first
  end

  def can_render?
    return true if previous_chapter.nil?

    previous_chapter.content.present?
  end
end
